// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vfcskgmphudiznbdbcgr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmY3NrZ21waHVkaXpuYmRiY2dyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMzAxMTcsImV4cCI6MjA2MDkwNjExN30.rz-yM2H17zjG3eRT6MKNKrvJiEN-Tfw7btba2TlDLGI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);